##====---- appveyor.yml                                               ----====##
# CI for OpenCppCoverage.
# Nuget generation is just to be compatible with the default project files.
#

# fetch repository as a zip archive
shallow_clone: true

skip_branch_with_pr: true
skip_commits:
  files:
  - .github/
  - .gitignore
  - BuildThirdPartyDependencies.bat
  - CreateRelease.bat
  - LICENSE.txt
  - '**/*.md'
  - '**/*.filters'

cache:
- C:\Tools\vcpkg\installed #-> appveyor.yml # Delete cache on change
- C:\Tools\vcpkg\packages #-> appveyor.yml # required for nuget generation
- C:\Tools\vcpkg\vcpkg.exe

image:
- Visual Studio 2017

platform:
- x86
- x64

configuration:
- Debug
- Release

environment:
  matrix:
  - DEPENDENCIES: HEAD
  - DEPENDENCIES: FIXED
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    TOOLCHAIN_FILE: 'C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake'
    VCPKG_SHA1: 2ac7527b40b1dbeb7856b9f763362c1e139e2ca9


install:
# Install latest version of vcpkg.exe
- cd C:\Tools\vcpkg && git pull --quiet
- ps: |
    if ( $(vcpkg upgrade) -match "^Warning: Different source.*for vcpkg" ) {
      .\bootstrap-vcpkg.bat 1>$null
      vcpkg integrate install 1>$null
    }
# Use a fixed versions of all dependencies
- ps: |
    if ( "$env:DEPENDENCIES" -eq "FIXED" ) {
      git checkout $env:VCPKG_SHA1 --quiet
    }
# Only build Release or Debug versions (for most packages)
- ps: |
    if ( "$env:CONFIGURATION" -eq "Release") {
      $triplet_build = 'set(VCPKG_BUILD_TYPE release)'
    } else {
      $triplet_build = 'set(VCPKG_BUILD_TYPE debug)'
    }
    $triplet_file = ".\triplets\${env:PLATFORM}-windows.cmake"
    $triplet_build | Out-File ${triplet_file} -Encoding ascii -Append
# Display cache state
- vcpkg list
- vcpkg update
# Updating cached dependencies
- ps: |
    if (!($(vcpkg upgrade) -match "^All installed packages are up-to-date")) {
      vcpkg upgrade --no-dry-run
    }
# Install new dependencies
- vcpkg install poco:%PLATFORM%-windows
- vcpkg install protobuf:%PLATFORM%-windows
- vcpkg install gtest:%PLATFORM%-windows
- vcpkg install ctemplate:%PLATFORM%-windows
- vcpkg install boost-optional:%PLATFORM%-windows
- vcpkg install boost-filesystem:%PLATFORM%-windows
- vcpkg install boost-algorithm:%PLATFORM%-windows
- vcpkg install boost-container:%PLATFORM%-windows
- vcpkg install boost-program-options:%PLATFORM%-windows
- vcpkg install boost-regex:%PLATFORM%-windows
- vcpkg install boost-range:%PLATFORM%-windows
- vcpkg install boost-log:%PLATFORM%-windows
- vcpkg install boost-property-tree:%PLATFORM%-windows
- vcpkg install boost-spirit:%PLATFORM%-windows
- vcpkg install boost-uuid:%PLATFORM%-windows
- vcpkg install boost-locale:%PLATFORM%-windows
- vcpkg install boost-iostreams:%PLATFORM%-windows
- vcpkg install range-v3:%PLATFORM%-windows
- >-
  vcpkg export
  poco:%PLATFORM%-windows
  protobuf:%PLATFORM%-windows
  gtest:%PLATFORM%-windows
  ctemplate:%PLATFORM%-windows
  boost-optional:%PLATFORM%-windows
  boost-filesystem:%PLATFORM%-windows
  boost-algorithm:%PLATFORM%-windows
  boost-container:%PLATFORM%-windows
  boost-program-options:%PLATFORM%-windows
  boost-regex:%PLATFORM%-windows
  boost-range:%PLATFORM%-windows
  boost-log:%PLATFORM%-windows
  boost-property-tree:%PLATFORM%-windows
  boost-spirit:%PLATFORM%-windows
  boost-uuid:%PLATFORM%-windows
  boost-locale:%PLATFORM%-windows
  boost-iostreams:%PLATFORM%-windows
  range-v3:%PLATFORM%-windows
  --nuget --nuget-id=ThirdParty --nuget-version=1.2.0
- ps: >-
    C:\Tools\vcpkg\downloads\tools\nuget-*-windows\nuget.exe
    install ThirdParty
    -Source C:\Tools\vcpkg
    -OutputDirectory $env:APPVEYOR_BUILD_FOLDER

before_build:
- cd %APPVEYOR_BUILD_FOLDER%

build_script:
- >-
  MSBuild
  -nologo
  -verbosity:minimal
  -p:Configuration="%CONFIGURATION%"
  -p:Platform="%PLATFORM%"
  -logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
